apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-frontend
  template:
    metadata:
      labels:
        app: ml-frontend
    spec:
      containers:
      - name: ml-frontend
        image: ml-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ml-frontend
spec:
  selector:
    app: ml-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
